Update SQLLite.yml

diff --git a/.github/workflows/SQLLite.yml b/.github/workflows/SQLLite.yml
--- a/.github/workflows/SQLLite.yml
+++ b/.github/workflows/SQLLite.yml
@@ -19,6 +19,7 @@ jobs:
           server-name: localhost
           instance-name: SQLExpress
           sa-password: "Post@123"
+          sa-user: "sa"  # Use double quotes if the value contains special characters
           admin-password: "Post@123" #${{ secrets.SQL_ADMIN_PASSWORD }}
           config-only: false
 
@@ -35,13 +36,13 @@ jobs:
       - name: Allow Remote Connections
         run: |
           # Enable TCP/IP protocol
-          sqlcmd -S localhost,1433 -P "Post@123" -Q "EXEC sp_configure 'remote access', 1; RECONFIGURE;"
+          sqlcmd -S localhost,1433 -U "sa" -P "Post@123" -Q "EXEC sp_configure 'remote access', 1; RECONFIGURE;"
 
       - name: Build and Deploy Database
         run: |
           dotnet build
-          # sqlcmd -S localhost\SQLExpress -U sa -P "Post@123" -d product -i ./create-database.sql || echo "Database creation failed: $?"
-          sqlcmd -S localhost\SQLExpress -U sa -P "Post@123" -Q "SELECT @@VERSION" || echo "Connection failed: $?"
+          # sqlcmd -S localhost\SQLExpress -U "sa" -P "Post@123" -d product -i ./create-database.sql || echo "Database creation failed: $?"
+          sqlcmd -S localhost\SQLExpress -U "sa" -P "Post@123" -Q "SELECT @@VERSION" || echo "Connection failed: $?"
           dotnet test --configuration Release --logger trx /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
-          sqlcmd -S localhost\SQLExpress -U sa -P "Post@123" -d learning -i ./db-scripts/your-script.sql || echo "Connection failed: $?"
+          sqlcmd -S localhost\SQLExpress -U "sa" -P "Post@123" -d learning -i ./db-scripts/your-script.sql || echo "Connection failed: $?"
       # Add additional steps as needed for your specific setup
