Update SQLLite.yml

diff --git a/.github/workflows/SQLLite.yml b/.github/workflows/SQLLite.yml
--- a/.github/workflows/SQLLite.yml
+++ b/.github/workflows/SQLLite.yml
@@ -21,7 +21,15 @@ jobs:
           sa-password: "Post@123"
           admin-password: "Post@123" #${{ secrets.SQL_ADMIN_PASSWORD }}
           config-only: false
-
+      - name: Check SQL Server Port
+        run: |
+          nc -zv localhost 1433  # Adjust hostname/IP if needed
+          if [ $? -eq 0 ]; then
+          echo "SQL Server is likely running on port 1433."
+          else
+          echo "Error: SQL Server does not appear to be running on port 1433."
+          exit 1  # Indicate failure to the workflow
+          fi
       - name: Build and Deploy Database
         run: |
           dotnet build
